name: Sync example project to Atlas template
on:
  push:
    branches:
      - main
    paths:
      - 'examples/next/getting-started/**'
jobs:
  sync_example_project_to_atlas_template:
    runs-on: ubuntu-latest
    env:
      CHECKOUT_DIR_NAME: ${{ github.event.repository.name }}
      SOURCE_REPO: ${{ github.event.repository.full_name }}
      SOURCE_AFTER_SHA: ${{ github.event.after }}
      TARGET_REPO: wpengine/faust-atlas-hello-world
      TARGET_BRANCH: main
      SYNC_DIR: examples/next/getting-started # No trailing slash
      GIT_EMAIL: bot@wpengine.com
      GIT_NAME: WP Engine Bot
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SYNC_ATLAS_TEMPLATE_SSH_PRIVATE_KEY }}
      - name: Sync Atlas Template
        run: |
          # Store the code we want to push to the target in "source" dir
          cd ../
          mkdir source

          # Rsync all files in SYNC_DIR to the "source" dir
          # Using -a, the archive flag, to preserve ownership and permissions
          # Using --no-compress as the sync is between local devices
          cd $CHECKOUT_DIR_NAME
          rsync -a --no-compress $SYNC_DIR/ ../source/
          cd ../

          # Clone the target repo, and rsync it's .git dir to the "source" dir
          git clone git@github.com:$TARGET_REPO.git target
          cd target
          rsync -a --no-compress .git ../source
          cd ../

          cd source

          # This is the committer who will show up in the target repo
          git config user.email "$GIT_EMAIL"
          git config user.name "$GIT_NAME"

          # Add all the recent changes non-existent in the target
          git add .

          git status

          # If there are changes, commit them
          git diff-index --quiet HEAD || git commit -m "Automatic sync from $SOURCE_REPO@$SOURCE_AFTER_SHA"

          # Push to the target branch
          git push origin $TARGET_BRANCH
