name: Test Packages
on: pull_request
jobs:
  test_packages:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        version: [16, 18]
    permissions:
      checks: write
      pull-requests: write
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: rm package-lock.json

      - name: Install
        run: npm install

      - run: npm run build

      - name: Code Coverage for Core Package
        uses: ./.github/actions/run-coverage
        with:
          working-directory: packages/core

      - name: Code Coverage for React Package
        uses: ./.github/actions/run-coverage
        with:
          working-directory: packages/react

      - name: Code Coverage for Next Package
        uses: ./.github/actions/run-coverage
        with:
          working-directory: packages/next
